name: transifex
on:
  push:
    paths:
    - _locales/en/messages.json
    branches:
    - main
jobs:
  push-messages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: transifex/cli-action@v2
      with:
        token: ${{ secrets.TX_TOKEN }}
